
package cn.itcast.cxfserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherService", targetNamespace = "http://cxfserver.itcast.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfoByCityName", targetNamespace = "http://cxfserver.itcast.cn/", className = "cn.itcast.cxfserver.GetInfoByCityName")
    @ResponseWrapper(localName = "getInfoByCityNameResponse", targetNamespace = "http://cxfserver.itcast.cn/", className = "cn.itcast.cxfserver.GetInfoByCityNameResponse")
    public String getInfoByCityName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
