
package cn.itcast.crm.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cn.itcast.crm.service.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.itcast.cn/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateFixedAreaId", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.UpdateFixedAreaId")
    @ResponseWrapper(localName = "updateFixedAreaIdResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.UpdateFixedAreaIdResponse")
    public void updateFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByAddress", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByAddress")
    @ResponseWrapper(localName = "findByAddressResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByAddressResponse")
    public String findByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findTelephone", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindTelephone")
    @ResponseWrapper(localName = "findTelephoneResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindTelephoneResponse")
    public Customer findTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByCustomerBirthday", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByCustomerBirthday")
    @ResponseWrapper(localName = "findByCustomerBirthdayResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByCustomerBirthdayResponse")
    public List<Customer> findByCustomerBirthday();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "active", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.Active")
    @ResponseWrapper(localName = "activeResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.ActiveResponse")
    public void active(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephoneAndPassword", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByTelephoneAndPassword")
    @ResponseWrapper(localName = "findByTelephoneAndPasswordResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByTelephoneAndPasswordResponse")
    public Customer findByTelephoneAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByEmailAndPassword", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByEmailAndPassword")
    @ResponseWrapper(localName = "findByEmailAndPasswordResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByEmailAndPasswordResponse")
    public Customer findByEmailAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.RegistResponse")
    public void regist(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
